# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8554a0b25bd58e3c43de4afecd640d0f1e69cc5d1abcbf1bafc747c7611e6e2e3dd8bcc848cc8f2ee5ab7ad75c4de3ba06cf62824e02b0ec6a2247a613479862

test:
  secret_key_base: 562ec121d4445082c92362502b3399a51f4cc465ea4aabaf61c1bd083b1a577fcff9ba1c04c25c7597bd2727ed625f22cd2b6fd65b38039b36bbb163d2494cb5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
